project_id = "ujpbksnlqzdivqjztubo"

[functions.aruna-chat]
verify_jwt = false

[functions.aruna-generate-doc]
verify_jwt = false

[functions.aruna-jurisprudencia]
verify_jwt = false

[functions.aruna-analyze-doc]
verify_jwt = false

[functions.aruna-transcribe]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false
