import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.95.3";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const SYSTEM_PROMPT = `Você é a ARUNA, assistente jurídica especialista em análise de documentos jurídicos.

Sua tarefa é analisar documentos jurídicos de forma detalhada e profissional.

Para cada documento, você deve fornecer:

1. **Tipo de Documento** — Identifique (petição, contrato, procuração, sentença, acórdão, etc.)
2. **Resumo Executivo** — Sintetize o conteúdo em 3-5 frases
3. **Partes Envolvidas** — Liste autores, réus, requerentes, outorgantes, etc.
4. **Pontos-Chave** — Destaque os argumentos, cláusulas ou decisões mais importantes
5. **Fundamentos Legais** — Identifique leis, artigos e jurisprudência citados
6. **Riscos e Observações** — Aponte possíveis riscos, inconsistências ou pontos de atenção
7. **Sugestões** — Recomende melhorias, contra-argumentos ou próximos passos

Formatação:
- Use Markdown estruturado com títulos e subtítulos
- Use listas para pontos-chave
- Destaque trechos importantes em negrito
- Use blocos de citação para transcrições do documento
- Use emojis moderadamente: 📄 ⚖️ ⚠️ ✅ 📋 🔍`;

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { document_id, organization_id, analysis_type, custom_instructions } = await req.json();

    if (!document_id || !organization_id) {
      return new Response(
        JSON.stringify({ error: "ID do documento e organização são obrigatórios." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY is not configured");

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Get document metadata
    const { data: docData, error: docError } = await supabase
      .from("documentos")
      .select("*")
      .eq("id", document_id)
      .eq("organization_id", organization_id)
      .single();

    if (docError || !docData) {
      return new Response(
        JSON.stringify({ error: "Documento não encontrado." }),
        { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Download file from storage
    const { data: fileData, error: fileError } = await supabase.storage
      .from("documentos")
      .download(docData.file_path);

    if (fileError || !fileData) {
      console.error("Storage download error:", fileError);
      return new Response(
        JSON.stringify({ error: "Erro ao baixar o documento do armazenamento." }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Extract text content
    let documentContent = "";
    const fileType = docData.file_type || docData.file_name?.split(".").pop()?.toLowerCase() || "";

    if (["txt", "md", "text/plain", "text/markdown"].includes(fileType)) {
      documentContent = await fileData.text();
    } else if (["text/html", "html"].includes(fileType)) {
      documentContent = await fileData.text();
    } else {
      // For markdown files generated by ARUNA
      documentContent = await fileData.text();
    }

    if (!documentContent || documentContent.trim().length < 10) {
      return new Response(
        JSON.stringify({ error: "Não foi possível extrair texto do documento. Apenas documentos de texto (.txt, .md) são suportados para análise no momento." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Truncate if too long (keep first 15000 chars for AI context)
    const maxChars = 15000;
    const truncated = documentContent.length > maxChars;
    const contentForAnalysis = truncated
      ? documentContent.slice(0, maxChars) + "\n\n[... documento truncado para análise ...]"
      : documentContent;

    const analysisTypes: Record<string, string> = {
      completa: "Realize uma análise completa e detalhada do documento.",
      resumo: "Faça um resumo executivo conciso do documento.",
      riscos: "Foque na identificação de riscos, cláusulas abusivas e pontos de atenção.",
      argumentos: "Identifique os principais argumentos jurídicos e sugira contra-argumentos.",
      clausulas: "Analise as cláusulas do documento detalhadamente, identificando obrigações e direitos de cada parte.",
    };

    const analysisInstruction = analysisTypes[analysis_type] || analysisTypes.completa;

    const userPrompt = `Analise o seguinte documento jurídico:

**Nome do arquivo:** ${docData.file_name}
**Tipo:** ${fileType}
${truncated ? "⚠️ *Documento truncado — apenas os primeiros 15.000 caracteres foram incluídos.*\n" : ""}

---

${contentForAnalysis}

---

**Instrução de análise:** ${analysisInstruction}
${custom_instructions ? `**Instruções adicionais do usuário:** ${custom_instructions}` : ""}`;

    const response = await fetch(
      "https://ai.gateway.lovable.dev/v1/chat/completions",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${LOVABLE_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "google/gemini-3-flash-preview",
          messages: [
            { role: "system", content: SYSTEM_PROMPT },
            { role: "user", content: userPrompt },
          ],
          stream: true,
        }),
      }
    );

    if (!response.ok) {
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: "Muitas requisições. Tente novamente em alguns segundos." }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: "Créditos de IA esgotados." }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const text = await response.text();
      console.error("AI gateway error:", response.status, text);
      return new Response(
        JSON.stringify({ error: "Erro ao conectar com a IA." }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    return new Response(response.body, {
      headers: { ...corsHeaders, "Content-Type": "text/event-stream" },
    });
  } catch (e) {
    console.error("aruna-analyze-doc error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Erro desconhecido" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
